"use strict";var e;Object.defineProperty(exports,"__esModule",{value:!0}),!function(e,t){for(var r in t)Object.defineProperty(e,r,{enumerable:!0,get:t[r]})}(exports,{default:function(){return v},readHwp:function(){return b}});const t=require("node:fs/promises"),r=require("node:http"),n=require("node:https"),a=require("node:url"),i=require("hwp.js"),o=(e=require("turndown"))&&e.__esModule?e:{default:e},p={0:"",10:"\n",13:"\n"},l=e=>{if("string"==typeof e.value)return e.value;if("number"==typeof e.value){let t=p[e.value];if("string"==typeof t)return t}return 0===e.type&&"number"==typeof e.value?String.fromCharCode(e.value):""},s=e=>e.content.map(l).join(""),u=e=>e.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;"),c=e=>{let t=s(e);return`<p>${u(t)}</p>`},f=(e,t=0)=>new Promise((i,o)=>{let p=new a.URL(e);("https:"===p.protocol?n.get:r.get)(p,r=>{let{statusCode:n=0,headers:l}=r;if(n>=300&&n<400&&l.location){if(t>=5){r.resume(),o(Error(`Too many redirects while fetching ${e}`));return}let n=new a.URL(l.location,p).toString();r.destroy(),f(n,t+1).then(i).catch(o);return}if(n>=400){r.resume(),o(Error(`Request to ${e} failed with status code ${n}`));return}let s=[];r.on("data",e=>{s.push("string"==typeof e?Buffer.from(e):e)}),r.on("end",()=>i(Buffer.concat(s))),r.on("error",o)}).on("error",o)}),d=(e,t={})=>{let r={...t.parseOptions??{},type:"buffer"},n=(0,i.parse)(e,r).sections.flatMap(e=>e.content).map(s).map(e=>e.replace(/\r\n/g,"\n").replace(/\r/g,"\n"));return!1===t.preserveParagraphBreaks?n.join(""):n.join("\n")},m=e=>e.replace(/<p>\s*<\/p>/g,"").replace(/<p><br><\/p>/g,"").replace(/<p>&nbsp;<\/p>/g,"").replace(/\n\s*\n\s*\n+/g,"\n\n").replace(/<p>[\s\u00a0]+<\/p>/g,""),g=(e,t={})=>{let r={...t.parseOptions??{},type:"buffer"},n=(0,i.parse)(e,r).sections.flatMap(e=>e.content).map(c).join("\n");return n=m(n),`<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>HWP Document</title>
  <style>
    body { font-family: 'Malgun Gothic', '맑은 고딕', sans-serif; line-height: 1.6; max-width: 800px; margin: 0 auto; padding: 20px; }
    p { margin: 10px 0; }
  </style>
</head>
<body>
${n}
</body>
</html>`},h=()=>new o.default({headingStyle:"atx",codeBlockStyle:"fenced",emDelimiter:"_"}),y=e=>{let t=h(),r=e.match(/<body>([\s\S]*?)<\/body>/),n=r?r[1]:e,a=t.turndown(n);return a.replace(/\n\s*\n\s*\n+/g,"\n\n").trim()},w=(e,t={})=>y(g(e,t)),b=async(e,r="plain",n={})=>{let a;if(Buffer.isBuffer(e))a=e;else if("string"==typeof e)a=e.trim().startsWith("http://")||e.trim().startsWith("https://")?await f(e.trim()):await (0,t.readFile)(e);else throw Error("Invalid source type. Must be a Buffer, file path string, or URL string.");switch(r){case"html":return g(a,n);case"markdown":return w(a,n);default:return d(a,n)}},v=b;